#highlighter: pygments
#pygments: true
#markdown: redcarpet
name: Cyberdyne Systems
description: A tech log
url: https://corrupted.io
plugins_dir:  _plugins
layouts_dir:  _layouts
data_dir:     _data
includes_dir: _includes
excerpt_separator: <!--more-->

include: [".well-known"]

# Filtering Content
show_drafts: null
limit_posts: 0
future:      false
unpublished: false

gems: [jekyll-paginate]

plugins:
  - jekyll-redirect-from

paginate: 10
paginate_path: "blog/page:num"

defaults:
-
    scope:
        path: ""
        type: "posts"
    values:
        layout: "default"
        author: "Jason Barbier"
-
    scope:
        path: ""
        type: "pages"
    values:
        layout: "default"
        author: "Jason Barbier"
