name: Corrupted.io
description: A tech log
url: https://corrupted.io
og_image: /img/og-default.png
layouts_dir:  _layouts
data_dir:     _data
excerpt_separator: <!--more-->

include: [".well-known"]

# Filtering Content
show_drafts: null
limit_posts: 0
future:      false
unpublished: false

plugins:
  - jekyll-redirect-from
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

feed:
  path: /blog/feed.xml

paginate: 10
paginate_path: "blog/page:num"

social:
  name: "Jason Barbier"
  links:
    - https://twitter.com/slaughterhut
    - https://www.linkedin.com/in/jas-bar
    - https://github.com/kusuriya
    - https://masto.hackers.town/@kusuriya

defaults:
-
    scope:
        path: ""
        type: "posts"
    values:
        layout: "default"
        author: "Jason Barbier"
-
    scope:
        path: ""
        type: "pages"
    values:
        layout: "default"
        author: "Jason Barbier"
